# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Physicophilia
author:
    name: Snigdho Chakraborty
    email: snigdho.chakraborty@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Through this website I target a wide range of audience in order to provide them with an easy access to key concepts, tools and interpretations in Nuclear and Particle Physics.
  Such concepts play an important role in Research, but are generally not discussed in any university level courses, or books. I try to articulate these fundamental 
  stuff that I learn from recent research articles, with stuff that we are regularly taught in undergraduate and post-graduate courses. This website in a way is to inspire others
  and motivate them towards Science and Research in Particle Physics:)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://snigdhos.com
#github_username:  snigdhochakraborty

social_links:
    twitter: jekyllrb
    github:  snigdhochakraborty
    instagram: snigdho.ch
# Build settings
theme: minima

minima:
  skin:classic

#paginate: 5
#paginator.next_page_path
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



